version: '2'
services:
  mysql-development:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app_development
      TZ: Asia/Tokyo
    expose:
      - '3306'
    volumes:
      - mysql-development-data:/var/lib/mysql
      - ./mysql5.6:/etc/mysql/conf.d

  mysql-test:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app_test
      TZ: Asia/Tokyo
    expose:
      - '3306'
    volumes:
      - mysql-test-data:/var/lib/mysql
      - ./mysql5.6:/etc/mysql/conf.d


  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BUNDLE_JOBS: 4
      BUNDLE_PATH: /usr/src/app/vendor/bundle
    command: bin/server
    ports:
      - '13000:3000'
    volumes:
      - .:/usr/src/app
      - bundle-data:/usr/src/app/vendor/bundle
      - node_modules-data:/usr/src/app/node_modules
      - log-data:/usr/src/app/log
    links:
      - mysql-test
      - mysql-development
      
volumes:
  mysql-development-data:
    driver: local
  mysql-test-data:
    driver: local
  bundle-data:
    driver: local
  node_modules-data:
    driver: local
  log-data:
    driver: local